STEPS = step0_repl.csproj step1_read_print.csproj step2_eval.csproj step3_env.csproj \
	step4_if_fn_do.csproj step5_tco.csproj step6_file.csproj \
	step7_quote.csproj step8_macros.csproj step9_try.csproj stepA_mal.csproj

$(STEPS):
	true

all:

clean:
